---

- name: Deploy all apps via Podman container
  hosts: all

  vars:
    hetzner_api_key: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      39323230633062363338333539313936313161663038313634643466313239373533393138353230
      6135633165613234613363343038333130346434326232360a386364393735373361656236626362
      66653930383631643938623263363530313539616631356136616564326631393065343464373839
      3863383166386133640a363131396331313733376135306563663931646634613566376335623936
      32363061336661613163333364346530353938396538626265393261626261393466666139613839
      3061376535376533623564656237316435393130626338386565

  tasks:
    - name: Create podman network for caddy
      containers.podman.podman_network:
        name: caddy_connect
        state: present

    - name: Create caddy directories
      ansible.builtin.file:
        path: "/data/{{ item }}"
        state: directory
      loop:
        - caddy
        - caddy/data
        - caddy/config

    - name: Copy Caddyfile
      register: caddyfile_result
      ansible.builtin.copy:
        src: Caddyfile
        dest: /data/caddy/Caddyfile

    - name: Ensure Caddy is running
      register: caddy_container_result
      containers.podman.podman_container:
        name: caddy
        image: "docker.io/caddy:2.7.6-alpine@sha256:2e1d4592f1718bb47645da5a83a846fe19094f18e6c921fdf56d174f05c63213" # yamllint disable-line
        image_strict: true
        state: started
        network:
          - caddy_connect
        publish:
          - "80:80"
          - "443:443"
          - "443:443/udp"
        volumes:
          - /data/caddy/Caddyfile:/etc/caddy/Caddyfile
          - /data/caddy/data:/data
          - /data/caddy/config:/config
          - /var/www:/srv

    - name: Reload Caddy
      when: caddyfile_result is changed and caddy_container_result is not changed # yamllint disable-line
      containers.podman.podman_container_exec:
        name: caddy
        workdir: /etc/caddy
        command: caddy reload

    - name: Create vhost directories
      ansible.builtin.file:
        path: "/var/www/{{ item }}"
        state: directory
      loop:
        - citizenalpha.de
        - citizenalpha.de/www
        - citizenalpha.de/www/htdocs

    - name: Add deploy user for website
      ansible.builtin.user:
        name: deploy-website
        state: present
        password: "!"
        shell: /usr/bin/sh
        create_home: true

    - name: Add ssh key to deploy-website
      ansible.posix.authorized_key:
        user: deploy-website
        state: present
        exclusive: true
        key: "{{ lookup('file', 'files/deploy-website.pub') }}"

    - name: Make deploy-website owner of website
      ansible.builtin.file:
        path: "/var/www/citizenalpha.de/www/htdocs"
        owner: deploy-website
        group: deploy-website

    - name: Create bind-mount for htdocs of citizenalpha.de
      ansible.builtin.mount:
        src: /var/www/citizenalpha.de/www/htdocs
        path: /home/deploy-website/htdocs
        fstype: none
        opts: bind
        state: mounted

    - name: Create podman network for chasquid
      containers.podman.podman_network:
        name: chasquid_connect
        state: present

    - name: Create casquid directories
      ansible.builtin.file:
        path: "/data/{{ item }}"
        state: directory
      loop:
        - "chasquid_conf"
        - "chasquid_conf/certs"
        - "chasquid_conf/certs/citizenalpha.de"
        - "chasquid_conf/domains"
        - "chasquid_conf/domains/citizenalpha.de"
        - "chasquid_data"
        - "lego"

    - name: Copy Chasquid config
      register: chasquid_result
      ansible.builtin.copy:
        src: chasquid.conf
        dest: /data/chasquid_conf/chasquid.conf

    - name: Copy Chasquid dkim key
      ansible.builtin.copy:
        src: chasquid_dkim_20240605.pem
        dest: "/data/chasquid_conf/domains/citizenalpha.de/dkim:20240605.pem"
        mode: 0640

    - name: Copy Chasquid user db
      ansible.builtin.copy:
        src: chasquid_citizenalpha_de_user_db
        dest: /data/chasquid_conf/domains/citizenalpha.de/users
        mode: 0640

    - name: Check presence of chasquid certificate
      ansible.builtin.stat:
        path: /data/lego/certificates/citizenalpha.de.crt
      register: chasquid_cert_result

    - name: Create chasquid certificate
      when: not chasquid_cert_result.stat.exists
      register: lego_result
      containers.podman.podman_container:
        name: lego
        image: docker.io/goacme/lego:latest
        command:
          - --email
          - hallo@citizenalpha.de
          - --accept-tos
          - --dns
          - hetzner
          - -d
          - citizenalpha.de
          - run
        state: started
        env:
          HETZNER_API_KEY: "{{ hetzner_api_key }}"
        volumes:
          - "/data/lego:/.lego"

    - name: Copy chasquid certificate
      when: lego_result is changed
      ansible.builtin.copy:
        remote_src: /data/lego/certificates/citizenalpha.de.crt
        dest: /data/chasquid_conf/certs/citizenalpha.de/fullchain.pem
        mode: 0600

    - name: Copy chasquid certificate key
      when: lego_result is changed
      ansible.builtin.copy:
        remote_src: /data/lego/certificates/citizenalpha.de.key
        dest: /data/chasquid_conf/certs/citizenalpha.de/privkey.pem
        mode: 0600

    - name: Ensure Chasquid is running
      register: chasquid_container_result
      containers.podman.podman_container:
        name: chasquid
        image: "ghcr.io/citizenalpha-project/chasquid:latest"
        image_strict: true
        state: started
        network:
          - chasquid_connect
        volumes:
          - "/data/chasquid_data:/var/lib/chasquid"
          - "/data/chasquid_conf:/etc/chasquid"

    - name: Restart Chasquid
      when: chasquid_result is changed and chasquid_container_result is not changed # yamllint disable-line
      containers.podman.podman_container_exec:
        name: chasquid
        force_restart: true

    - name: Create offen directories
      ansible.builtin.file:
        path: "/data/offen"
        state: directory

    - name: Create offen directories 2
      ansible.builtin.file:
        path: "/data/offen/data"
        state: directory
        owner: 10000
        group: 10001

    - name: Copy Offen env file
      register: offen_env_result
      ansible.builtin.copy:
        src: offen.env
        dest: /data/offen/offen.env
        mode: 0600

    - name: Ensure Offen is running
      register: offen_container_result
      containers.podman.podman_container:
        name: offen
        image: "docker.io/offen/offen:v1.4.2@sha256:4a69f8cbcdbff26505e728ad803a9b8ff6752bd10330749633bc507276e52c5d" # yamllint disable-line
        image_strict: true
        state: started
        env_file:
          - /data/offen/offen.env
        network:
          - caddy_connect
          - chasquid_connect
        volumes:
          - "/data/offen/data:/var/opt/offen"

    - name: Restart Offen
      when: offen_env_result is changed and offen_container_result is not changed # yamllint disable-line
      containers.podman.podman_container:
        name: offen
        state: started
        force_restart: true
