---

- name: Deploy all apps via Podman container
  hosts: all

  tasks:
    - name: Create podman network for caddy
      containers.podman.podman_network:
        name: caddy_connect
        state: present

    - name: Create caddy directories
      ansible.builtin.file:
        path: "/data/{{ item }}"
        state: directory
      loop:
        - caddy
        - caddy/data
        - caddy/config

    - name: Copy Caddyfile
      register: caddyfile_result
      ansible.builtin.copy:
        src: Caddyfile
        dest: /data/caddy/Caddyfile

    - name: Ensure Caddy is running
      register: caddy_container_result
      containers.podman.podman_container:
        name: caddy
        image: "docker.io/caddy:2.7.6-alpine@sha256:2e1d4592f1718bb47645da5a83a846fe19094f18e6c921fdf56d174f05c63213" # yamllint disable-line
        image_strict: true
        state: started
        network:
          - caddy_connect
        publish:
          - "80:80"
          - "443:443"
          - "443:443/udp"
        volumes:
          - /data/caddy/Caddyfile:/etc/caddy/Caddyfile
          - /data/caddy/data:/data
          - /data/caddy/config:/config
          - /var/www:/srv

    - name: Reload Caddy
      when: caddyfile_result is changed and caddy_container_result is not changed # yamllint disable-line
      containers.podman.podman_container_exec:
        name: caddy
        workdir: /etc/caddy
        command: caddy reload

    - name: Create vhost directories
      ansible.builtin.file:
        path: "/var/www/{{ item }}"
        state: directory
      loop:
        - citizenalpha.de
        - citizenalpha.de/www
        - citizenalpha.de/www/htdocs

    - name: Add deploy user for website
      ansible.builtin.user:
        name: deploy-website
        state: present
        password: "!"
        shell: /usr/bin/sh
        create_home: true

    - name: Add ssh key to deploy-website
      ansible.posix.authorized_key:
        user: deploy-website
        state: present
        exclusive: true
        key: "{{ lookup('file', 'files/deploy-website.pub') }}"

    - name: Make deploy-website owner of website
      ansible.builtin.file:
        path: "/var/www/citizenalpha.de/www/htdocs"
        owner: deploy-website
        group: deploy-website

    - name: Create bind-mount for htdocs of citizenalpha.de
      ansible.builtin.mount:
        src: /var/www/citizenalpha.de/www/htdocs
        path: /home/deploy-website/htdocs
        fstype: none
        opts: bind
        state: mounted

    - name: Create offen directories
      ansible.builtin.file:
        path: "/data/offen"
        state: directory

    - name: Create offen directories 2
      ansible.builtin.file:
        path: "/data/offen/data"
        state: directory
        owner: 10000
        group: 10001

    - name: Copy Offen env file
      register: offen_env_result
      ansible.builtin.copy:
        src: offen.env
        dest: /data/offen/offen.env
        mode: 0600

    - name: Ensure Offen is running
      register: offen_container_result
      containers.podman.podman_container:
        name: offen
        image: "docker.io/offen/offen:v1.4.2@sha256:4a69f8cbcdbff26505e728ad803a9b8ff6752bd10330749633bc507276e52c5d" # yamllint disable-line
        image_strict: true
        state: started
        env_file:
          - /data/offen/offen.env
        network:
          - caddy_connect
        volumes:
          - "/data/offen/data:/var/opt/offen"

    - name: Restart Offen
      when: offen_env_result is changed and offen_container_result is not changed # yamllint disable-line
      containers.podman.podman_container:
        name: offen
        state: started
        force_restart: true
